### ISSUE TITLE
Show Auto Clean

### ISSUE THREAD

**Issue by icolombi** [atxbyea/samsungrac#112]
Hi there,

I'm using the old generation device integration on port 2878.

My device supports auto clean, but I can't find a switch on Home Assistant to enable this feature.

How can I be able to control the auto clean feature with HA?

Thanks.

![image](https://github.com/user-attachments/assets/72c1d740-b2be-4031-a9f5-bf9e731b8702)

**Comment by GSzabados** [comment]
To your configuration.yaml.

```
switch:
  - platform: template
      auto_clean:
        friendly_name: "AC Auto Clean"
        value_template: "{{ is_state_attr('climate.YOUR_AC_NAME', 'auto_clean', 'on') }}"
        turn_on:
          service: climate.climate_ip_set_property
          data:
            entity_id: climate.YOUR_AC_NAME
            auto_clean: 'on'
        turn_off:
          service: climate.climate_ip_set_property
          data:
            entity_id: climate.YOUR_AC_NAME
            auto_clean: 'off'
```
