### ISSUE TITLE
MIMH04-EN: Support INDOOR1 and INDOOR2

### ISSUE THREAD

**Issue by peperoni60** [atxbyea/samsungrac#115]
My heat pump supports two EHS Heating circuits (1: floor heating (FBH), 2: radiators (HK)). So it is not possible to use `/config/custom_components/climate_ip_addendum/samsung_smartthings_hvac.yaml` as it uses `INDOOR` only. I created two copies of the said yaml file to a location outside of the repository location and and suffixed them with 1 rsp. 2. Inside the files I changed `INDOOR` to `INDOOR1` rsp. `INDOOR2`.  In the configuration file `climate.yaml` I used the following lines:
``` yaml
# Wärmepumpe
# ---------------------------------
# hot water controller
- platform: climate_ip
  name: Samsung EHS DHW
  config_file: /config/custom_components/climate_ip/samsung_smartthings_dhw.yaml
  ip_address: api.smartthings.com
  device_id: <my-device-id>
  token: !secret smartthings_token
# heating controller 1 (fbh)
- platform: climate_ip
  name: Samsung EHS Heating FBH
  config_file: /config/custom_components/climate_ip_addendum/samsung_smartthings_hvac_1.yaml
  ip_address: api.smartthings.com
  device_id: <my-device-id>
  token: !secret smartthings_token
# heating controller 2 (hk)
- platform: climate_ip
  name: Samsung EHS Heating HK
  config_file: /config/custom_components/climate_ip_addendum/samsung_smartthings_hvac_2.yaml
  ip_address: api.smartthings.com
  device_id: <my-device-id>
  token: !secret smartthings_token
```
where `<my-device-id>` is the id of my heat pump.

Could you please provide these additional files in the repository, as the heat pump can support up to 2 heating circuits
