### ISSUE TITLE
Possible to get info about power consumption?

### ISSUE THREAD

**Issue by Blodskjegg** [atxbyea/samsungrac#36]
In the SmartAir app I can view power consumption of my heater, is this possible in the integration?

**Comment by atxbyea** [comment]
@Blodskjegg will investigate

**Comment by jackdalma** [comment]
add to the end of the file samsung_2878.yaml

    used_power:
      type: number
      status_template: '{% for key, value in device_state.items() %}{% if key == "AC_ADD2_USEDPOWER" %}{{value}}{% endif %}{% endfor %}'
for home assistant add a template sensor:

```
template:
  - sensor:
      - name: "NAME"
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: "{{ state_attr('YOUR_CLIMATE.ENTITY', 'used_power') * 0.1 }}"
        attributes:         
          last_reset: '1970-01-01T00:00:00+00:00'
```

**Comment by Blodskjegg** [comment]
> add to the end of the file samsung_2878.yaml
> 
> ```
> used_power:
>   type: number
>   status_template: '{% for key, value in device_state.items() %}{% if key == "AC_ADD2_USEDPOWER" %}{{value}}{% endif %}{% endfor %}'
> ```
> 
> for home assistant add a template sensor:
> 
> ```
> template:
>   - sensor:
>       - name: "NAME"
>         unit_of_measurement: "kWh"
>         state_class: total_increasing
>         device_class: energy
>         state: "{{ state_attr('YOUR_CLIMATE.ENTITY', 'used_power') * 0.1 }}"
>         attributes:         
>           last_reset: '1970-01-01T00:00:00+00:00'
> ```

That worked, thanks a lot.
Tho, not sure how I can configure the power consumption so I can see it by day or hour.
Now it seems to show total consumption since pump was installed?
I see that I can edit "last reset", but I'm sure there is another way of doing this other than edit last reset every day?

**Comment by jackdalma** [comment]
you can add utility_meter if you are not going to use the integrated energy usage of home assistant.
[https://www.home-assistant.io/integrations/utility_meter/](https://www.home-assistant.io/integrations/utility_meter/)
```
utility_meter:
  energy:
    source: sensor.NAME
    cycle: daily
```

all possible cycle value are quarter-hourly, hourly, daily, weekly, monthly, bimonthly, quarterly and yearly 
:)
